#!/usr/bin/bash
# script that transfers a file from our client to a server

# Check if number of arguments is less than 3, display usage
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
