#!/usr/bin/env bash
# configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/
sudo service nginx start
