#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# Update package index and install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

config="\nlisten load-balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 530789-web-01 100.26.240.110:80 check
	server 530789-web-02 54.157.160.220:80 check"

echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
