#!/usr/bin/env bash
# Configures Nginx to run as the nginx user and listen on all active IPs on port 8080

# Update package lists
sudo apt-get update

# Stop Apache2 if running
sudo pkill apache2

# Modify nginx configuration to run as nginx user
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Modify nginx configuration to listen on port 8080
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# Start nginx service
sudo service nginx start
