#!/usr/bin/env bash
# Configures Nginx to run as the nginx user and listen on port 8080

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
